### ISSUE TITLE
Import ARCv2 architecture patch

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-qemu#14]
Import the ARCv2 architecture patch (currently based on QEMU 4.2) into the `zephyr-qemu` repository.

https://github.com/zephyrproject-rtos/sdk-ng/blob/master/meta-zephyr-sdk/recipes-devtools/qemu/files/0006-Add-support-for-ARCv2-architecture.patch

Merged into `sdk-ng` in https://github.com/zephyrproject-rtos/sdk-ng/pull/208

Since the `zephyr-qemu` repository is based on QEMU 5.0 at the time of writing, the patch will need to be converted to work with it.

**Comment by stephanosio** [comment]
@abrodkin Do you have any estimate on when you will have the QEMU 5.0 port of this patch?

**Comment by abrodkin** [comment]
@stephanosio in fact we do have re-based on top of v5.0 version so if needed I may post those changes somewhere. Just let me know in which form you prefer to get it and when.

**Comment by stephanosio** [comment]
> @stephanosio in fact we do have re-based on top of v5.0 version so if needed I may post those changes somewhere. Just let me know in which form you prefer to get it and when.

@abrodkin That's great. Git `.patch` format would be nice, so I can import your commits here and in the [`sdk-ng` QEMU 5.0 PR](https://github.com/zephyrproject-rtos/sdk-ng/pull/200).

**Comment by abrodkin** [comment]
There seems to be no way to create a pull-request if I didn't clone from your repo, so you may just cherry-pick this one - https://github.com/abrodkin/qemu/commit/d2fb10a24959bcbc53bd543a49cfd3ff3a334670. It's based on your current master.
Tried to run both `qemu_arc_em` & `qemu_arc_hs` and it worked as good as 4.2.
